export const MATCHES = [
  // Group stage
  {id:'m001',rd:'Group stage',grp:'A',aest:'Fri 12 Jun 5am',hf:'🇲🇽',af:'🇿🇦',h:'Mexico',a:'South Africa'},
  {id:'m002',rd:'Group stage',grp:'A',aest:'Fri 12 Jun 12pm',hf:'🇰🇷',af:'🇨🇿',h:'South Korea',a:'Czechia'},
  {id:'m003',rd:'Group stage',grp:'B',aest:'Sat 13 Jun 2am',hf:'🇨🇦',af:'🇧🇦',h:'Canada',a:'Bosnia & Herz.'},
  {id:'m004',rd:'Group stage',grp:'C',aest:'Sun 14 Jun 5am',hf:'🇧🇷',af:'🇲🇦',h:'Brazil',a:'Morocco'},
  {id:'m005',rd:'Group stage',grp:'D',aest:'Sun 14 Jun 8am',hf:'🇺🇸',af:'🇵🇾',h:'USA',a:'Paraguay'},
  {id:'m006',rd:'Group stage',grp:'C',aest:'Mon 15 Jun 8am',hf:'🇦🇺',af:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',h:'Australia',a:'Scotland'},
  {id:'m007',rd:'Group stage',grp:'E',aest:'Mon 15 Jun 12pm',hf:'🇩🇪',af:'🇨🇼',h:'Germany',a:'Curaçao'},
  {id:'m008',rd:'Group stage',grp:'F',aest:'Mon 15 Jun 3pm',hf:'🇳🇱',af:'🇯🇵',h:'Netherlands',a:'Japan'},
  {id:'m009',rd:'Group stage',grp:'E',aest:'Mon 15 Jun 6pm',hf:'🇨🇮',af:'🇪🇨',h:'Ivory Coast',a:'Ecuador'},
  {id:'m010',rd:'Group stage',grp:'F',aest:'Mon 15 Jun 10pm',hf:'🇸🇪',af:'🇹🇳',h:'Sweden',a:'Tunisia'},
  {id:'m011',rd:'Group stage',grp:'H',aest:'Tue 16 Jun 2am',hf:'🇪🇸',af:'🇨🇻',h:'Spain',a:'Cape Verde'},
  {id:'m012',rd:'Group stage',grp:'G',aest:'Tue 16 Jun 5am',hf:'🇧🇪',af:'🇪🇬',h:'Belgium',a:'Egypt'},
  {id:'m013',rd:'Group stage',grp:'H',aest:'Tue 16 Jun 8am',hf:'🇸🇦',af:'🇺🇾',h:'Saudi Arabia',a:'Uruguay'},
  {id:'m014',rd:'Group stage',grp:'G',aest:'Tue 16 Jun 11am',hf:'🇮🇷',af:'🇳🇿',h:'Iran',a:'New Zealand'},
  {id:'m015',rd:'Group stage',grp:'I',aest:'Wed 17 Jun 5am',hf:'🇫🇷',af:'🇸🇳',h:'France',a:'Senegal'},
  {id:'m016',rd:'Group stage',grp:'I',aest:'Wed 17 Jun 8am',hf:'🇮🇶',af:'🇳🇴',h:'Iraq',a:'Norway'},
  {id:'m017',rd:'Group stage',grp:'J',aest:'Wed 17 Jun 11am',hf:'🇦🇷',af:'🇩🇿',h:'Argentina',a:'Algeria'},
  {id:'m018',rd:'Group stage',grp:'J',aest:'Wed 17 Jun 2pm',hf:'🇦🇹',af:'🇯🇴',h:'Austria',a:'Jordan'},
  {id:'m019',rd:'Group stage',grp:'K',aest:'Thu 18 Jun 3pm',hf:'🇵🇹',af:'🇨🇩',h:'Portugal',a:'DR Congo'},
  {id:'m020',rd:'Group stage',grp:'L',aest:'Thu 18 Jun 6pm',hf:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',af:'🇭🇷',h:'England',a:'Croatia'},
  {id:'m021',rd:'Group stage',grp:'L',aest:'Thu 18 Jun 9pm',hf:'🇬🇭',af:'🇵🇦',h:'Ghana',a:'Panama'},
  {id:'m022',rd:'Group stage',grp:'K',aest:'Fri 19 Jun 12pm',hf:'🇺🇿',af:'🇨🇴',h:'Uzbekistan',a:'Colombia'},
  {id:'m023',rd:'Group stage',grp:'A',aest:'Fri 19 Jun 2am',hf:'🇨🇿',af:'🇿🇦',h:'Czechia',a:'South Africa'},
  {id:'m024',rd:'Group stage',grp:'B',aest:'Fri 19 Jun 5am',hf:'🇨🇭',af:'🇧🇦',h:'Switzerland',a:'Bosnia & Herz.'},
  {id:'m025',rd:'Group stage',grp:'B',aest:'Fri 19 Jun 8am',hf:'🇨🇦',af:'🇶🇦',h:'Canada',a:'Qatar'},
  {id:'m026',rd:'Group stage',grp:'A',aest:'Fri 19 Jun 11am',hf:'🇲🇽',af:'🇰🇷',h:'Mexico',a:'South Korea'},
  {id:'m027',rd:'Group stage',grp:'D',aest:'Sat 20 Jun 5am',hf:'🇺🇸',af:'🇦🇺',h:'USA',a:'Australia'},
  {id:'m028',rd:'Group stage',grp:'C',aest:'Sat 20 Jun 8am',hf:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',af:'🇲🇦',h:'Scotland',a:'Morocco'},
  {id:'m029',rd:'Group stage',grp:'D',aest:'Sat 20 Jun 11am',hf:'🇹🇷',af:'🇵🇾',h:'Türkiye',a:'Paraguay'},
  {id:'m030',rd:'Group stage',grp:'C',aest:'Sat 20 Jun 11am',hf:'🇧🇷',af:'🇭🇹',h:'Brazil',a:'Haiti'},
  {id:'m031',rd:'Group stage',grp:'F',aest:'Sun 21 Jun 3pm',hf:'🇳🇱',af:'🇸🇪',h:'Netherlands',a:'Sweden'},
  {id:'m032',rd:'Group stage',grp:'E',aest:'Sun 21 Jun 6pm',hf:'🇩🇪',af:'🇨🇮',h:'Germany',a:'Ivory Coast'},
  {id:'m033',rd:'Group stage',grp:'E',aest:'Sun 21 Jun 10pm',hf:'🇪🇨',af:'🇨🇼',h:'Ecuador',a:'Curaçao'},
  {id:'m034',rd:'Group stage',grp:'F',aest:'Mon 22 Jun 2am',hf:'🇹🇳',af:'🇯🇵',h:'Tunisia',a:'Japan'},
  {id:'m035',rd:'Group stage',grp:'H',aest:'Mon 22 Jun 2am',hf:'🇪🇸',af:'🇸🇦',h:'Spain',a:'Saudi Arabia'},
  {id:'m036',rd:'Group stage',grp:'G',aest:'Mon 22 Jun 5am',hf:'🇧🇪',af:'🇮🇷',h:'Belgium',a:'Iran'},
  {id:'m037',rd:'Group stage',grp:'H',aest:'Mon 22 Jun 8am',hf:'🇺🇾',af:'🇨🇻',h:'Uruguay',a:'Cape Verde'},
  {id:'m038',rd:'Group stage',grp:'G',aest:'Mon 22 Jun 11am',hf:'🇳🇿',af:'🇪🇬',h:'New Zealand',a:'Egypt'},
  {id:'m039',rd:'Group stage',grp:'J',aest:'Tue 23 Jun 3am',hf:'🇦🇷',af:'🇦🇹',h:'Argentina',a:'Austria'},
  {id:'m040',rd:'Group stage',grp:'I',aest:'Tue 23 Jun 7am',hf:'🇫🇷',af:'🇮🇶',h:'France',a:'Iraq'},
  {id:'m041',rd:'Group stage',grp:'I',aest:'Tue 23 Jun 10am',hf:'🇳🇴',af:'🇸🇳',h:'Norway',a:'Senegal'},
  {id:'m042',rd:'Group stage',grp:'J',aest:'Tue 23 Jun 1pm',hf:'🇯🇴',af:'🇩🇿',h:'Jordan',a:'Algeria'},
  {id:'m043',rd:'Group stage',grp:'K',aest:'Wed 24 Jun 3am',hf:'🇵🇹',af:'🇺🇿',h:'Portugal',a:'Uzbekistan'},
  {id:'m044',rd:'Group stage',grp:'L',aest:'Wed 24 Jun 6am',hf:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',af:'🇬🇭',h:'England',a:'Ghana'},
  {id:'m045',rd:'Group stage',grp:'L',aest:'Wed 24 Jun 9am',hf:'🇵🇦',af:'🇭🇷',h:'Panama',a:'Croatia'},
  {id:'m046',rd:'Group stage',grp:'K',aest:'Wed 24 Jun 12pm',hf:'🇨🇴',af:'🇨🇩',h:'Colombia',a:'DR Congo'},
  {id:'m047',rd:'Group stage',grp:'B',aest:'Thu 25 Jun 5am',hf:'🇨🇭',af:'🇨🇦',h:'Switzerland',a:'Canada'},
  {id:'m048',rd:'Group stage',grp:'B',aest:'Thu 25 Jun 5am',hf:'🇧🇦',af:'🇶🇦',h:'Bosnia & Herz.',a:'Qatar'},
  {id:'m049',rd:'Group stage',grp:'C',aest:'Thu 25 Jun 8am',hf:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',af:'🇧🇷',h:'Scotland',a:'Brazil'},
  {id:'m050',rd:'Group stage',grp:'C',aest:'Thu 25 Jun 8am',hf:'🇲🇦',af:'🇭🇹',h:'Morocco',a:'Haiti'},
  {id:'m051',rd:'Group stage',grp:'A',aest:'Thu 25 Jun 11am',hf:'🇨🇿',af:'🇲🇽',h:'Czechia',a:'Mexico'},
  {id:'m052',rd:'Group stage',grp:'A',aest:'Thu 25 Jun 11am',hf:'🇿🇦',af:'🇰🇷',h:'South Africa',a:'South Korea'},
  {id:'m053',rd:'Group stage',grp:'E',aest:'Fri 26 Jun 6am',hf:'🇪🇨',af:'🇩🇪',h:'Ecuador',a:'Germany'},
  {id:'m054',rd:'Group stage',grp:'E',aest:'Fri 26 Jun 6am',hf:'🇨🇼',af:'🇨🇮',h:'Curaçao',a:'Ivory Coast'},
  {id:'m055',rd:'Group stage',grp:'F',aest:'Fri 26 Jun 9am',hf:'🇯🇵',af:'🇸🇪',h:'Japan',a:'Sweden'},
  {id:'m056',rd:'Group stage',grp:'F',aest:'Fri 26 Jun 9am',hf:'🇹🇳',af:'🇳🇱',h:'Tunisia',a:'Netherlands'},
  {id:'m057',rd:'Group stage',grp:'D',aest:'Fri 26 Jun 12pm',hf:'🇹🇷',af:'🇺🇸',h:'Türkiye',a:'USA'},
  {id:'m058',rd:'Group stage',grp:'D',aest:'Fri 26 Jun 12pm',hf:'🇵🇾',af:'🇦🇺',h:'Paraguay',a:'Australia'},
  {id:'m059',rd:'Group stage',grp:'I',aest:'Sat 27 Jun 5am',hf:'🇳🇴',af:'🇫🇷',h:'Norway',a:'France'},
  {id:'m060',rd:'Group stage',grp:'I',aest:'Sat 27 Jun 5am',hf:'🇸🇳',af:'🇮🇶',h:'Senegal',a:'Iraq'},
  {id:'m061',rd:'Group stage',grp:'H',aest:'Sat 27 Jun 10am',hf:'🇨🇻',af:'🇸🇦',h:'Cape Verde',a:'Saudi Arabia'},
  {id:'m062',rd:'Group stage',grp:'H',aest:'Sat 27 Jun 10am',hf:'🇺🇾',af:'🇪🇸',h:'Uruguay',a:'Spain'},
  {id:'m063',rd:'Group stage',grp:'G',aest:'Sat 27 Jun 1pm',hf:'🇪🇬',af:'🇮🇷',h:'Egypt',a:'Iran'},
  {id:'m064',rd:'Group stage',grp:'G',aest:'Sat 27 Jun 1pm',hf:'🇳🇿',af:'🇧🇪',h:'New Zealand',a:'Belgium'},
  {id:'m065',rd:'Group stage',grp:'L',aest:'Sun 28 Jun 7am',hf:'🇵🇦',af:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',h:'Panama',a:'England'},
  {id:'m066',rd:'Group stage',grp:'L',aest:'Sun 28 Jun 7am',hf:'🇭🇷',af:'🇬🇭',h:'Croatia',a:'Ghana'},
  {id:'m067',rd:'Group stage',grp:'K',aest:'Sun 28 Jun 9:30am',hf:'🇨🇴',af:'🇵🇹',h:'Colombia',a:'Portugal'},
  {id:'m068',rd:'Group stage',grp:'K',aest:'Sun 28 Jun 9:30am',hf:'🇨🇩',af:'🇺🇿',h:'DR Congo',a:'Uzbekistan'},
  {id:'m069',rd:'Group stage',grp:'J',aest:'Sun 28 Jun 12pm',hf:'🇩🇿',af:'🇦🇹',h:'Algeria',a:'Austria'},
  {id:'m070',rd:'Group stage',grp:'J',aest:'Sun 28 Jun 12pm',hf:'🇯🇴',af:'🇦🇷',h:'Jordan',a:'Argentina'},
  // Knockouts
  {id:'m071',rd:'Round of 32',grp:'R32',aest:'Tue 1 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m072',rd:'Round of 32',grp:'R32',aest:'Tue 1 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m073',rd:'Round of 32',grp:'R32',aest:'Wed 2 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m074',rd:'Round of 32',grp:'R32',aest:'Wed 2 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m075',rd:'Round of 32',grp:'R32',aest:'Thu 3 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m076',rd:'Round of 32',grp:'R32',aest:'Thu 3 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m077',rd:'Round of 32',grp:'R32',aest:'Fri 4 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m078',rd:'Round of 32',grp:'R32',aest:'Fri 4 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m079',rd:'Round of 32',grp:'R32',aest:'Sat 5 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m080',rd:'Round of 32',grp:'R32',aest:'Sat 5 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m081',rd:'Round of 32',grp:'R32',aest:'Sun 6 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m082',rd:'Round of 32',grp:'R32',aest:'Sun 6 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m083',rd:'Round of 32',grp:'R32',aest:'Mon 7 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m084',rd:'Round of 32',grp:'R32',aest:'Mon 7 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m085',rd:'Round of 32',grp:'R32',aest:'Tue 8 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m086',rd:'Round of 32',grp:'R32',aest:'Tue 8 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m087',rd:'Quarterfinals',grp:'QF',aest:'Fri 11 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m088',rd:'Quarterfinals',grp:'QF',aest:'Sat 12 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m089',rd:'Quarterfinals',grp:'QF',aest:'Sun 13 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m090',rd:'Quarterfinals',grp:'QF',aest:'Sun 13 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m091',rd:'Semifinals',grp:'SF',aest:'Wed 16 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m092',rd:'Semifinals',grp:'SF',aest:'Thu 17 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m093',rd:'3rd Place',grp:'3P',aest:'Sun 20 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
  {id:'m094',rd:'Final',grp:'FIN',aest:'Mon 21 Jul',hf:'🏳',af:'🏳',h:'TBC',a:'TBC'},
]

export const ROUNDS = ['Group stage','Round of 32','Quarterfinals','Semifinals','3rd Place','Final']
export const COLORS = ['#185FA5','#3B6D11','#993C1D','#534AB7','#854F0B','#A32D2D','#0F6E56','#993556']
